/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.syscpd.telas;

import br.com.syscpd.conexaobd.ModuloConexao;
import br.com.syscpd.dao.GerarRelatorio_data;
import br.com.syscpd.model.Relatorio;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author teste
 */
public class TelaRelatorio extends javax.swing.JInternalFrame {

    Connection conexao = null;

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
        conexao = ModuloConexao.conector();
        rad_Ate.setSelected(true);
    }

    private void geraRelatorioAtUso() {

        int confirma = JOptionPane.showConfirmDialog(null, "Confirma impressão do relatorio", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            //imprime relatorio
            try {
                //Usando a clase jasperprint para preparar impressão de um relatorio
                JasperPrint print = JasperFillManager.fillReport("C:/Relatorio Ireport/UserAtendimento.jasper", null, conexao);
                //exibi o relatorio atraves da classe JasperViwer
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    private void geraRelatorioAt() {

        int confirma = JOptionPane.showConfirmDialog(null, "Confirma impressão do relatorio", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            //imprime relatorio
            try {
                //Usando a clase jasperprint para preparar impressão de um relatorio
                JasperPrint print = JasperFillManager.fillReport("C:/Relatorio Ireport/antendimento.jasper", null, conexao);
                //exibi o relatorio atraves da classe JasperViwer
                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    public void relatorio() {

        GerarRelatorio_data relatorio = new GerarRelatorio_data();
        String dataInicial;
        String dataFinal;
        SimpleDateFormat dataSimples = new SimpleDateFormat("yyyy-MM-dd");

        //dataInicial = dataSimples.format(this.rel_dateInicial.getDate());
        //dataFinal = dataSimples.format(this.rel_dateFinal.getDate());

        int confirma = JOptionPane.showConfirmDialog(null, "Confirma impressão do relatorio", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            //imprime relatorio
            try {
                //Usando a classe HashMap para criar um filtro
                HashMap data = new HashMap();
                HashMap data2 = new HashMap();
                
                //data1.put("dataInicial", Integer.parseInt(dataInicial));
                //data2.put("dataFinal", Integer.parseInt(dataFinal));

                //Usando a clase jasperprint para preparar impressão de um relatorio
                //JasperPrint print1 = JasperFillManager.fillReport("C:/Relatorio Ireport/Relatorio_por_data.jasper", data1, conexao);
                //JasperPrint print2 = JasperFillManager.fillReport("C:/Relatorio Ireport/oss.jasper", data2, conexao);
                
                //exibi o relatorio atraves da classe JasperViwer
                //JasperViewer.viewReport(print1, false);
                //JasperViewer.viewReport(print2, false);
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println("" + e);
            }
        }

        /**
         * dt.setDatainicial(dataInicial); dt.setDatafinal(dataFinal);
         *
         * relatorio.relatorioatendimentos(dt); try { int confirma =
         * JOptionPane.showConfirmDialog(null, "Confirma impressão do
         * relatorio", "Atenção", JOptionPane.YES_NO_OPTION); if (confirma ==
         * JOptionPane.YES_OPTION); //chamar o jasrper } catch (Exception e) {
         *
         * JOptionPane.showMessageDialog(null, e);
        }*
         */
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        btn_gerarRelatorio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rad_Ate = new javax.swing.JRadioButton();
        rad_At_uso = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        TexteMove = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Relatorios");
        setAlignmentX(10.0F);
        setAlignmentY(10.0F);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/syscpd/icones/relatorio_128x128.png"))); // NOI18N

        btn_gerarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/syscpd/icones/Gera_relatorio_64x64.png"))); // NOI18N
        btn_gerarRelatorio.setPreferredSize(new java.awt.Dimension(64, 64));
        btn_gerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerarRelatorioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Data inicial");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Atendimento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Atendimento X Usuário");

        buttonGroup1.add(rad_Ate);

        buttonGroup1.add(rad_At_uso);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rad_Ate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rad_At_uso)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rad_Ate)
                    .addComponent(rad_At_uso))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Data final");

        TexteMove.setText("Teste");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3)
                        .addContainerGap(125, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_gerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(TexteMove, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(TexteMove, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_gerarRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)))
                .addGap(51, 51, 51))
        );

        setBounds(450, 150, 650, 374);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerarRelatorioActionPerformed
        // Gera Relatorio
        relatorio();
//        String dataInicial;
//        String dataFinal;
//
//        SimpleDateFormat dataSimples = new SimpleDateFormat("yyyy-MM-dd");
//        dataInicial = dataSimples.format(this.rel_dateInicial.getDate());
//        dataFinal = dataSimples.format(this.rel_dateFinal.getDate());
//        
//        if (rad_At_uso.isSelected()) {
//            
//            geraRelatorioAtUso();
//
//            System.out.println("" + dataInicial);
//            System.out.println("" + dataFinal);
//            
//        } else if (rad_Ate.isSelected()) {
//
//            geraRelatorioAt();
//            System.out.println("Data Inicial " + dataInicial);
//            System.out.println("Data Final " + dataFinal);
//        } else {
//
//            JOptionPane.showMessageDialog(null, "Escolha tipo de relatorio !");
//        }
    }//GEN-LAST:event_btn_gerarRelatorioActionPerformed

    private void rel_dateInicialAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_rel_dateInicialAncestorAdded
        // TODO add your handling code here:
            geraRelatorioAt();
        //rel_dateInicial.getCalendar();
    }//GEN-LAST:event_rel_dateInicialAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TexteMove;
    private javax.swing.JButton btn_gerarRelatorio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rad_At_uso;
    private javax.swing.JRadioButton rad_Ate;
    // End of variables declaration//GEN-END:variables
}
